## MYSQL数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authoritymanagement?characterEncoding=utf-8&&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    
## thymeleaf的设置    
  thymeleaf:
    cache: false   
    encoding: utf-8
    mode: html5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    
## MYSQL数据源
logging:
  config: classpath:log4j2/logbak.xml
  
  
## mybatis的文件配置 type-aliases-package: com.example.entit
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
     
## server 端口 设置
server:
  port: 8089
  




      

 
    
